In [1]:
import numpy as np

## 合并操作

In [2]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [3]:
x

array([1, 2, 3])

In [4]:
y

array([3, 2, 1])

In [5]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [6]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

In [7]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
np.concatenate([A, A], axis=1)   # axis 默认是0 代表第一维度（行），  1代表第二个维度（列）

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [9]:
# 把向量合并入矩阵
z = np.array([666, 666, 666])

np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [10]:
# 上面出错的原因是 A 和 z 的维数不一样，A是2维，z是一维。 concatenate 操作只能处理维数一样的数据。
# 把 z 转换为2维，再合并
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [11]:
# 另外一个操作 vstack 可以智能的把 一维的向量拼到 矩阵中
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [12]:
# 同样有 hstack
B = np.full((2, 2), 88)
B

array([[88, 88],
       [88, 88]])

In [13]:
np.hstack([A, B])

array([[ 1,  2,  3, 88, 88],
       [ 4,  5,  6, 88, 88]])

## 分割操作

In [14]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x1, x2, x3 = np.split(x, [3, 7])  # 以第3个，第7个元素作为分割点，切成3段

In [16]:
x1

array([0, 1, 2])

In [17]:
x2

array([3, 4, 5, 6])

In [18]:
x3

array([7, 8, 9])

In [19]:
# 也可以按照列分割
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
A1, A2 = np.split(A, [2], axis=1)

In [21]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [22]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [23]:
# vsplit

upper, lower = np.vsplit(A, [2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
# hsplit
left, right = np.hsplit(A, [2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [26]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])