In [1]:
import numpy as np

## 手动创建  numpy.array

In [2]:
np.array([i for i in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## numpy.zeros

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## numpy.ones

In [6]:
np.ones(shape=(3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## numpy.full

In [8]:
np.full(shape=(3, 5), fill_value=3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

## arange

In [9]:
# python 中的 range
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
# numpy 中的 arange 使用相似的语法
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# 和 python 的 range 不同的是 ，步长可以用 小数
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [12]:
# 默认步长是 1
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 起始点也可以省略，默认是0
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [14]:
# 自动生成 [0, 20] 包含0和20的闭区间，个数为10的等差数列
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [15]:
np.linspace(0, 20, 11)
# 生成步长是2的数列： (20-0)/(11-1)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [16]:
np.random.randint(0, 10)

1

In [17]:
np.random.randint(0, 10, size=5)

array([3, 1, 9, 8, 2])

In [18]:
# 区间是前闭后开的

In [19]:
np.random.randint(0, 10, size=(2, 3))

array([[4, 8, 8],
       [7, 6, 0]])

In [20]:
# 指定随机种子
np.random.seed(666)

np.random.randint(0, 10, size=(2, 3))

array([[2, 6, 9],
       [4, 3, 1]])

In [22]:
# 再来一次
np.random.seed(666)

np.random.randint(0, 10, size=(2, 3))

array([[2, 6, 9],
       [4, 3, 1]])

In [23]:
# 默认参数情况下，random 生成的是 0~1 间的随机浮点数， 满足均匀分布
np.random.random()

0.5080663057670065

In [24]:
np.random.random(5)

array([0.20024754, 0.74415417, 0.192892  , 0.70084475, 0.29322811])

In [26]:
np.random.random((2, 3))

array([[0.77447945, 0.00510884, 0.11285765],
       [0.11095367, 0.24766823, 0.0232363 ]])

In [27]:
# 改为正态分布，均值为0，方差为1
np.random.normal()

-0.8819217518648244

In [28]:
# 均值为10， 方差为100
np.random.normal(10, 100)

135.32703893505888

In [29]:
np.random.normal(10, 100, (2, 3))

array([[  12.80167238,   50.8557194 ,   63.92856473],
       [-144.98470081,   82.9464519 ,  -22.69547657]])

## 在 notebook 中查看库文档

In [30]:
# 在 notebook 中查看 numpy 相关方法的文档
np.random.normal?

In [31]:
# 也可以查模块
np.random?

In [32]:
# 也可以自己输出在 notebook 中
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution