In [1]:
import numpy as np

## 数乘

In [3]:
L = np.arange(10)
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions
数乘只是 universal fun 的一个，还有其他的 universal fun：

In [19]:
X = np.arange(1, 16).reshape(3, -1)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [21]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [23]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [24]:
X // 2 # 整除

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [25]:
X ** 3

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000],
       [1331, 1728, 2197, 2744, 3375]])

In [26]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [27]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [28]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [30]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [31]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [32]:
np.exp(X)  # == np.power(e, X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [33]:
np.power(3, X) # == 3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [34]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [35]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [36]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [37]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [38]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [39]:
A + B

array([[10, 11],
       [12, 13]])

In [40]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [41]:
A * B  # 这样的计算在数学上是没有定义的

array([[ 0, 10],
       [20, 30]])

In [42]:
A / B  # 这样的计算在数学上是没有定义的

array([[0. , 0.1],
       [0.2, 0.3]])

In [43]:
A.dot(B)  # 真正的矩阵乘法，内积

array([[10, 10],
       [50, 50]])

In [44]:
A.T  # 转置

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [45]:
v = np.array([1, 2])
v

array([1, 2])

In [46]:
v + A    # 这样的计算在数学上是没有定义的

array([[1, 3],
       [3, 5]])

In [47]:
[v]

[array([1, 2])]

In [48]:
[v] * A.shape[0]

[array([1, 2]), array([1, 2])]

In [49]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [50]:
np.vstack([v] * A.shape[0]) + A  # 在数学上，相同shape的两个矩阵相加才有定义

array([[1, 3],
       [3, 5]])

In [56]:
# 上面用 vstack 的方法还可以用更加贴切的方式：
np.tile(v, (2, 1))  # 按照 行x2，列x1 的方式铺“瓷砖“

array([[1, 2],
       [1, 2]])

##### 乘法

In [60]:
v

array([1, 2])

In [61]:
A

array([[0, 1],
       [2, 3]])

In [57]:
v * A # 这样的计算在数学上是没有定义的

array([[0, 2],
       [2, 6]])

In [58]:
v.dot(A) # 内积

array([4, 7])

In [62]:
# 矩阵和向量的内积，numpy 会自动判断，后面的向量应该是已行向量还是列向量的方式参与运算
A.dot(v)

array([2, 8])

In [64]:
# 其实这里的 v 是被转换为列向量参与运算的
A.dot(v.T)

array([2, 8])

## 矩阵的逆

In [65]:
A

array([[0, 1],
       [2, 3]])

In [67]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [68]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [69]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [70]:
# 不是所有的矩阵都可逆的
X = np.arange(16).reshape((2, 8))
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [72]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [73]:
# 上面错误提示，矩阵可逆至少要是一个方阵

In [77]:
# 但是实际数学上需要对 非方阵求 逆，就可以用 伪逆
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -5.20417043e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [78]:
pinvX.shape

(8, 2)

In [79]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 6.66133815e-16,  1.00000000e+00]])