In [1]:
import numpy as np

## 向量的聚合运算

In [6]:
L = np.random.rand(100)
L

array([0.69463377, 0.8352934 , 0.520246  , 0.65179654, 0.21862213,
       0.91604427, 0.92884894, 0.71207987, 0.32516767, 0.72211307,
       0.97923853, 0.77201867, 0.67884729, 0.94863088, 0.83790154,
       0.34965658, 0.49780364, 0.73331532, 0.12131571, 0.31527606,
       0.74356149, 0.51255207, 0.1658109 , 0.93132459, 0.8075073 ,
       0.11287419, 0.55779886, 0.71785284, 0.48616905, 0.08798186,
       0.90700949, 0.1567882 , 0.91525833, 0.283028  , 0.27834613,
       0.3887495 , 0.89594879, 0.53473409, 0.82040994, 0.88522773,
       0.59974039, 0.94898655, 0.55127358, 0.84579954, 0.67436445,
       0.72067995, 0.22967972, 0.12684405, 0.17397743, 0.40741323,
       0.58624288, 0.68147728, 0.27364654, 0.40405458, 0.38270787,
       0.77880582, 0.51134777, 0.56556552, 0.33099969, 0.72713007,
       0.07564703, 0.13737584, 0.12673951, 0.1292686 , 0.69127674,
       0.26991876, 0.54853227, 0.8535308 , 0.74869823, 0.1708001 ,
       0.05751569, 0.64305582, 0.33722699, 0.8971003 , 0.63458

In [7]:
# 求和

np.sum(L)

52.97070403996034

In [8]:
np.min(L)

0.05751569286494618

In [9]:
np.max(L)

0.9792385275467272

## 矩阵的聚合运算

In [10]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.sum(X)

120

In [12]:
np.sum(X, axis=0)  # 每列的和，0是第一个维度，即行，sum是沿着行求和，或者理解为最后求得的是一个行向量

array([24, 28, 32, 36])

In [13]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [14]:
#  求积
np.prod(X)

0

In [15]:
np.prod(X + 1)

20922789888000

In [16]:
# 平均值
np.mean(X)

7.5

In [19]:
# 中位数
np.median(X)

7.5

In [20]:
# 百分位
np.percentile(X, q=50)

7.5

In [21]:
np.percentile(X, q=25)

3.75

In [22]:
# 方差
np.var(X)

21.25

In [23]:
# 标准差
np.std(X)

4.6097722286464435

In [24]:
x = np.random.normal(0, 1, size=1000000)  # 用正态分布来测试标准差
np.mean(x)

-0.0005189342341390211

In [25]:
np.std(x)

0.9993095408459391