In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

In [4]:
# 数组的维度
x.ndim

1

In [5]:
X.ndim

2

In [6]:
# 形状
x.shape

(10,)

In [7]:
X.shape

(3, 5)

In [8]:
# 大小，元素总数量
x.size

10

In [9]:
X.size

15

## 数据访问：索引和切片

In [10]:
x[3]

3

In [11]:
x[-1]

9

In [12]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
X[2, 2]

12

In [14]:
x[0:5]

array([0, 1, 2, 3, 4])

In [15]:
x[:5]

array([0, 1, 2, 3, 4])

In [16]:
x[5:]

array([5, 6, 7, 8, 9])

In [17]:
x[::2]   #步长

array([0, 2, 4, 6, 8])

In [18]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [21]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [22]:
X[0, :]  # 取一行

array([0, 1, 2, 3, 4])

In [23]:
X[:, 0]  # 取一列

array([ 0,  5, 10])

## 子矩阵和原矩阵共享数据问题

In [24]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [25]:
subX[0, 0] = 999
subX

array([[999,   1,   2],
       [  5,   6,   7]])

In [26]:
X

array([[999,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [27]:
# 让子矩阵和原矩阵脱离关系
subY = X[:2, :3].copy()

In [28]:
subY

array([[999,   1,   2],
       [  5,   6,   7]])

In [29]:
subY[0, 1] = 888
subY

array([[999, 888,   2],
       [  5,   6,   7]])

In [30]:
X

array([[999,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

## numpy.reshape

In [31]:
x.shape

(10,)

In [32]:
x.ndim

1

In [33]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
x  # 原数组并没有变

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x.reshape(5, -1)   # 自动计算

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
x.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
x.reshape(3, -1)   # 不能被整除，会报错

ValueError: cannot reshape array of size 10 into shape (3,newaxis)