In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, size=1000000)
x

array([-1.25024624, -2.27465701, -0.73989852, ..., -1.46565797,
       -0.10539828,  0.46875123])

## arg 运算

In [3]:
np.min(x)

-4.702369793986918

In [4]:
# 最小值所在索引
n = np.argmin(x)
n

46579

In [5]:
x[n]

-4.702369793986918

In [6]:
np.argmax(x)

677919

In [7]:
x[np.argmax(x)]

4.847750631372536

In [8]:
np.max(x)

4.847750631372536

## 排序和使用索引

In [9]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
# 乱序处理
np.random.shuffle(x)
x

array([ 7,  5,  8, 15, 11, 14, 13,  1,  3,  4, 10,  6,  9, 12,  2,  0])

In [12]:
# 排序，无副作用
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
# 原地排序
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
# 针对二维数组排序
X = np.random.randint(10, size=(4, 4))
X

array([[2, 5, 4, 3],
       [4, 0, 5, 2],
       [1, 3, 5, 8],
       [9, 2, 3, 1]])

In [17]:
np.sort(X, axis=0) # 沿着行的方向排序

array([[1, 0, 3, 1],
       [2, 2, 4, 2],
       [4, 3, 5, 3],
       [9, 5, 5, 8]])

In [18]:
 np.sort(X, axis=1) # 沿着列的方向排序

array([[2, 3, 4, 5],
       [0, 2, 4, 5],
       [1, 3, 5, 8],
       [1, 2, 3, 9]])

In [19]:
# 排序 arg 运算
np.random.shuffle(x)
x

array([ 7,  8,  6,  1, 15,  4, 10, 11,  0, 14,  9,  3,  2, 13,  5, 12])

In [20]:
np.argsort(x) # 把 x 排序后各元素在原数组的索引位置

array([ 8,  3, 12, 11,  5, 14,  2,  0,  1, 10,  6,  7, 15, 13,  9,  4])