In [1]:
import numpy as np

## 向量的 fancy indexing 操作

In [2]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
# 索引
x[3]

3

In [4]:
# 索引切片
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [5]:
# 如果要取跳跃的元素
[x[3], x[5], x[8]]

[3, 5, 8]

In [6]:
# 采用 fancy indexing
index = [3, 5, 8]
x[index]

array([3, 5, 8])

In [8]:
# 甚至可以从一维数组构建二维数组
index2 = np.array([[0, 2], 
                   [1, 3]])
x[index2]

array([[0, 2],
       [1, 3]])

## 矩阵的 fancy indexing 操作

In [9]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [11]:
X[0, col]

array([1, 2, 3])

In [12]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

## 基于布尔数组的 fancy indexing 操作

In [13]:
col = [True, False, True, True]
X[0, col]

array([0, 2, 3])

## numpy.array 中的比较

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [16]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [17]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [18]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [19]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [21]:
# 比较的应用

In [22]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
np.sum(x <=3)

4

In [24]:
np.count_nonzero(x <= 3)

4

In [25]:
np.any(x == 0)

True

In [26]:
np.any(x < 0)

False

In [27]:
np.all(x >= 0)

True

In [28]:
np.all(x > 0)

False

In [29]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
# 矩阵中偶数的个数
np.sum(X % 2 == 0)

8

In [38]:
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [39]:
np.sum(X % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [40]:
# 要注意逻辑判断的组合
np.sum((x > 3) & (x < 10))

6

In [41]:
# 上面的 & 两边不是一个 bool 值，而是一个矩阵，所以不能用 &&，反而 矩阵支持 &，即在每位上分别做位运算结果还是一个 矩阵

In [42]:
# 还有非运算
np.sum(~(x==0))

15

## fancy indexing 配合 比较运算的例子

In [43]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [44]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [49]:
# 获取 X 最后一列值能被3整除的所有行
X[X[:, -1] % 3 == 0]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])